/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.JForms;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author programa
 */
public class Dashboard extends javax.swing.JFrame {
    private Connection conn;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        try {
            // Cambia FlatLightLaf por el tema que quieras usar
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("No se pudo aplicar FlatLaf");
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    public Dashboard(Connection connection) {
        try {
            // Cambia FlatLightLaf por el tema que quieras usar
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("No se pudo aplicar FlatLaf");
        }
        initComponents();
        setLocationRelativeTo(null);
        conn = connection;
        cargarDatosCuentas();
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                cerrarConnection();
            }
        });
    }
    private void cerrarConnection(){
        if (conn != null) {
            try {
                conn.close();
                System.out.println("Connection closed.");
            } catch (SQLException e) {
                System.out.println("Error closing connection.");
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        singleDate1 = new raven.datetime.component.date.SingleDate();
        primerPanel = new javax.swing.JPanel();
        menuJTb = new javax.swing.JTabbedPane();
        transaccionesJPn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaPck = new com.github.lgooddatepicker.components.DatePicker();
        transaccionCmb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionTxt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ingresarBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        impuestoBtn = new javax.swing.JRadioButton();
        porcentajeLbl = new javax.swing.JLabel();
        porcentajeCmb = new javax.swing.JComboBox<>();
        cuentaLbl = new javax.swing.JLabel();
        cuentaCmb = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        montoTxt = new javax.swing.JFormattedTextField();
        cuentaDebeTxt = new javax.swing.JFormattedTextField();
        descuentoTxt = new javax.swing.JFormattedTextField();
        cuentaHaberTxt = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        diarioJPn = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        diarioTbl = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        mayorJPn = new javax.swing.JPanel();
        costosJPn = new javax.swing.JPanel();
        catalogoJPn = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuentasTbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        agregarCuentaBtn = new javax.swing.JButton();
        actualizarBtn = new javax.swing.JButton();
        barraJMn = new javax.swing.JMenuBar();
        archivoJMn = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        temasJMn = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        ayudaJMn = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        salirJMn = new javax.swing.JMenu();
        salirBtn = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Contable");

        primerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuJTb.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingreso de Transacciones");
        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N

        jLabel3.setText("Fecha realizada");
        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 1, 17)); // NOI18N

        fechaPck.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        transaccionCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Ingreso", "Salida", "Préstamo", "Interno" }));
        transaccionCmb.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        jLabel4.setText("Tipo de transacción");
        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 1, 17)); // NOI18N

        descripcionTxt.setColumns(20);
        descripcionTxt.setRows(5);
        descripcionTxt.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        jScrollPane2.setViewportView(descripcionTxt);

        jLabel5.setText("Monto");
        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 1, 17)); // NOI18N

        jLabel6.setText("Cuentas afectadas");
        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 1, 17)); // NOI18N

        jLabel7.setText("IVA");
        jLabel7.setFont(new java.awt.Font("JetBrains Mono", 1, 17)); // NOI18N

        ingresarBtn.setText("Ingresar transacción");
        ingresarBtn.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        ingresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Cuenta del debe:");
        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        jLabel9.setText("Cuenta del haber:");
        jLabel9.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        impuestoBtn.setText("Si");
        impuestoBtn.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        impuestoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impuestoBtnActionPerformed(evt);
            }
        });

        porcentajeLbl.setText("Porcentaje");
        porcentajeLbl.setEnabled(false);
        porcentajeLbl.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        porcentajeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "13%", "14%" }));
        porcentajeCmb.setEnabled(false);
        porcentajeCmb.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        cuentaLbl.setText("Cuenta");
        cuentaLbl.setEnabled(false);
        cuentaLbl.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        cuentaCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "115", "212" }));
        cuentaCmb.setEnabled(false);
        cuentaCmb.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        jLabel11.setText("Descuento");
        jLabel11.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        montoTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        montoTxt.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        cuentaDebeTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cuentaDebeTxt.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        descuentoTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        descuentoTxt.setText("0.00");
        descuentoTxt.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        cuentaHaberTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cuentaHaberTxt.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        jLabel12.setText("Descripción de la transacción");
        jLabel12.setFont(new java.awt.Font("JetBrains Mono", 1, 17)); // NOI18N

        javax.swing.GroupLayout transaccionesJPnLayout = new javax.swing.GroupLayout(transaccionesJPn);
        transaccionesJPn.setLayout(transaccionesJPnLayout);
        transaccionesJPnLayout.setHorizontalGroup(
            transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(transaccionesJPnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, transaccionesJPnLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, transaccionesJPnLayout.createSequentialGroup()
                        .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(transaccionesJPnLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(transaccionesJPnLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cuentaDebeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(transaccionesJPnLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(cuentaHaberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(transaccionesJPnLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(fechaPck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(transaccionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(transaccionesJPnLayout.createSequentialGroup()
                        .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transaccionesJPnLayout.createSequentialGroup()
                                .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(transaccionesJPnLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(descuentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(transaccionesJPnLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)
                                .addComponent(montoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(312, 312, 312)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(impuestoBtn)
                            .addGroup(transaccionesJPnLayout.createSequentialGroup()
                                .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(porcentajeLbl)
                                    .addComponent(cuentaLbl))
                                .addGap(49, 49, 49)
                                .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(porcentajeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cuentaCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(229, 229, 229))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaccionesJPnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ingresarBtn)
                .addGap(37, 37, 37))
        );
        transaccionesJPnLayout.setVerticalGroup(
            transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaccionesJPnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fechaPck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transaccionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaccionesJPnLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(montoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaccionesJPnLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(impuestoBtn)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(descuentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentajeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentajeLbl))
                .addGap(18, 18, 18)
                .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaccionesJPnLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(transaccionesJPnLayout.createSequentialGroup()
                        .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cuentaLbl)
                            .addComponent(cuentaCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cuentaDebeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(transaccionesJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cuentaHaberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ingresarBtn)
                .addGap(49, 49, 49))
        );

        menuJTb.addTab("Transacciones", transaccionesJPn);

        diarioTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Fecha", "Descripción", "Monto"
            }
        ));
        jScrollPane3.setViewportView(diarioTbl);
        if (diarioTbl.getColumnModel().getColumnCount() > 0) {
            diarioTbl.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Registro de Transacciones");
        jLabel10.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N

        javax.swing.GroupLayout diarioJPnLayout = new javax.swing.GroupLayout(diarioJPn);
        diarioJPn.setLayout(diarioJPnLayout);
        diarioJPnLayout.setHorizontalGroup(
            diarioJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diarioJPnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(diarioJPnLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diarioJPnLayout.setVerticalGroup(
            diarioJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diarioJPnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        menuJTb.addTab("Libro diario", diarioJPn);

        javax.swing.GroupLayout mayorJPnLayout = new javax.swing.GroupLayout(mayorJPn);
        mayorJPn.setLayout(mayorJPnLayout);
        mayorJPnLayout.setHorizontalGroup(
            mayorJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        mayorJPnLayout.setVerticalGroup(
            mayorJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );

        menuJTb.addTab("Balance", mayorJPn);

        javax.swing.GroupLayout costosJPnLayout = new javax.swing.GroupLayout(costosJPn);
        costosJPn.setLayout(costosJPnLayout);
        costosJPnLayout.setHorizontalGroup(
            costosJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        costosJPnLayout.setVerticalGroup(
            costosJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );

        menuJTb.addTab("Costos", costosJPn);

        cuentasTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Nombre", "Tipo"
            }
        ));
        cuentasTbl.setEnabled(false);
        cuentasTbl.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        jScrollPane1.setViewportView(cuentasTbl);
        if (cuentasTbl.getColumnModel().getColumnCount() > 0) {
            cuentasTbl.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cuentas de EDC Solutions");
        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N

        agregarCuentaBtn.setText("Agregar cuenta");
        agregarCuentaBtn.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        actualizarBtn.setText("Actualizar");
        actualizarBtn.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        actualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout catalogoJPnLayout = new javax.swing.GroupLayout(catalogoJPn);
        catalogoJPn.setLayout(catalogoJPnLayout);
        catalogoJPnLayout.setHorizontalGroup(
            catalogoJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoJPnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catalogoJPnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(catalogoJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(catalogoJPnLayout.createSequentialGroup()
                        .addComponent(actualizarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarCuentaBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        catalogoJPnLayout.setVerticalGroup(
            catalogoJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoJPnLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(catalogoJPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCuentaBtn)
                    .addComponent(actualizarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );

        menuJTb.addTab("Cátalogo de cuentas", catalogoJPn);

        primerPanel.add(menuJTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 800));
        menuJTb.getAccessibleContext().setAccessibleName("pestanas");

        barraJMn.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        archivoJMn.setText("Sistema");
        archivoJMn.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        jMenuItem8.setText("Realizar ajustes");
        jMenuItem8.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        archivoJMn.add(jMenuItem8);
        archivoJMn.add(jSeparator4);

        jMenuItem10.setText("Realizar Cierre Contable");
        jMenuItem10.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        archivoJMn.add(jMenuItem10);
        archivoJMn.add(jSeparator5);

        jMenuItem9.setText("Generar Estados Financieros");
        jMenuItem9.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        archivoJMn.add(jMenuItem9);

        barraJMn.add(archivoJMn);

        temasJMn.setText("Temas");
        temasJMn.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        jMenuItem6.setText("Tema Oscuro");
        jMenuItem6.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        temasJMn.add(jMenuItem6);

        jMenuItem7.setText("Tema Claro");
        jMenuItem7.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        temasJMn.add(jMenuItem7);

        barraJMn.add(temasJMn);

        ayudaJMn.setText("Ayuda");
        ayudaJMn.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Manual");
        jMenuItem1.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        ayudaJMn.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        jMenuItem2.setText("Soporte");
        ayudaJMn.add(jMenuItem2);
        ayudaJMn.add(jSeparator2);

        jMenuItem3.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        jMenuItem3.setText("Reportar problema");
        ayudaJMn.add(jMenuItem3);
        ayudaJMn.add(jSeparator3);

        jMenuItem4.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        jMenuItem4.setText("Buscar actualizaciones");
        ayudaJMn.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        jMenuItem5.setText("Acerca de");
        ayudaJMn.add(jMenuItem5);

        barraJMn.add(ayudaJMn);

        salirJMn.setText("Cerrar sesión");
        salirJMn.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N

        salirBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        salirBtn.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        salirBtn.setText("Salir");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        salirJMn.add(salirBtn);

        barraJMn.add(salirJMn);

        setJMenuBar(barraJMn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void impuestoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impuestoBtnActionPerformed
        boolean mostrar=false;
        if(impuestoBtn.isSelected()){
            mostrar=true;
        }

        mostrarImpuestos(mostrar);
    }//GEN-LAST:event_impuestoBtnActionPerformed

    private void ingresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBtnActionPerformed
        if(valido()){
            ingresarTransaccion();
        }
    }//GEN-LAST:event_ingresarBtnActionPerformed
    private boolean valido(){
        try{
            double monto = Double.parseDouble(montoTxt.getText());
            double descuento = Double.parseDouble(descuentoTxt.getText());
            if(monto<=0 || descuento<0){
                enviarError("Monto y Descuento deben ser positivos");
                return false;
            }
        }catch(Exception e){
            enviarError("Monto y Descuentos no pueden estar vacíos");
            return false;
        }
        try{
            if(cuentaDebeTxt.getText().isEmpty() || cuentaHaberTxt.getText().isEmpty()){
                enviarError("Los campos de las cuentas no pueden estar vacíos");
                return false;
            }
            int cuentaDebe = Integer.parseInt(cuentaDebeTxt.getText().trim());
            int cuentaHaber = Integer.parseInt(cuentaHaberTxt.getText().trim());
            String query = "SELECT COUNT(*) FROM sistemacontable.cuentas WHERE codigo = ?";

            // Verificar si ambas cuentas existen en el catálogo
            if (!existeEnCatalogo(query, cuentaDebe) || !existeEnCatalogo(query, cuentaHaber)) {
                enviarError("Las cuentas no coinciden con el catálogo");
                return false;
            }
        }catch(Exception e){
            enviarError("Erro al validar datos de las cuentas");
            return false;
        }
        if(descripcionTxt.getText().trim().isEmpty()){
            enviarError("Ingrese una descripción");
            return false;
        }
        return true;
    }
    private boolean existeEnCatalogo(String query, int cuenta) throws Exception {
        try (PreparedStatement stmt = conn.prepareStatement(query)) { // Usa la conexión existente
            stmt.setInt(1, cuenta);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt(1) > 0; // Devuelve true si la cuenta existe en el catálogo
                }
            }
        }
        return false; // Devuelve false si la cuenta no existe en el catálogo
    }
    private void enviarError(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje, "Error de transacción",JOptionPane.ERROR_MESSAGE);
    }
    
    private void ingresarTransaccion() {
        JOptionPane.showMessageDialog(null, "Transacción ingresada", "Transacción existosa",JOptionPane.PLAIN_MESSAGE);
    }
    private void actualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBtnActionPerformed
        cargarDatosCuentas();
    }//GEN-LAST:event_actualizarBtnActionPerformed

    public void cargarDatosCuentas() {
        String query = "SELECT codigo, nombre, tipo FROM sistemacontable.cuentas";

        try {
            // Crear un modelo de tabla y limpiarlo para añadir datos
            DefaultTableModel model = (DefaultTableModel) cuentasTbl.getModel();
            model.setRowCount(0); // Limpiar las filas existentes

            // Ejecutar la consulta
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            // Llenar el modelo de tabla con los datos del ResultSet
            while (rs.next()) {
                Object[] row = {
                    rs.getString("codigo"),
                    rs.getString("nombre"),
                    rs.getString("tipo")
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cargar datos: " + e.getMessage());
        }
    }
    private void mostrarImpuestos(boolean mostrar){
        cuentaCmb.setEnabled(mostrar);
        cuentaLbl.setEnabled(mostrar);
        porcentajeCmb.setEnabled(mostrar);
        porcentajeLbl.setEnabled(mostrar);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JButton agregarCuentaBtn;
    private javax.swing.JMenu archivoJMn;
    private javax.swing.JMenu ayudaJMn;
    private javax.swing.JMenuBar barraJMn;
    private javax.swing.JPanel catalogoJPn;
    private javax.swing.JPanel costosJPn;
    private javax.swing.JComboBox<String> cuentaCmb;
    private javax.swing.JFormattedTextField cuentaDebeTxt;
    private javax.swing.JFormattedTextField cuentaHaberTxt;
    private javax.swing.JLabel cuentaLbl;
    private javax.swing.JTable cuentasTbl;
    private javax.swing.JTextArea descripcionTxt;
    private javax.swing.JFormattedTextField descuentoTxt;
    private javax.swing.JPanel diarioJPn;
    private javax.swing.JTable diarioTbl;
    private com.github.lgooddatepicker.components.DatePicker fechaPck;
    private javax.swing.JRadioButton impuestoBtn;
    private javax.swing.JButton ingresarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPanel mayorJPn;
    private javax.swing.JTabbedPane menuJTb;
    private javax.swing.JFormattedTextField montoTxt;
    private javax.swing.JComboBox<String> porcentajeCmb;
    private javax.swing.JLabel porcentajeLbl;
    private javax.swing.JPanel primerPanel;
    private javax.swing.JMenuItem salirBtn;
    private javax.swing.JMenu salirJMn;
    private raven.datetime.component.date.SingleDate singleDate1;
    private javax.swing.JMenu temasJMn;
    private javax.swing.JComboBox<String> transaccionCmb;
    private javax.swing.JPanel transaccionesJPn;
    // End of variables declaration//GEN-END:variables

}
